# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Any

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref

from .models.gemini import (
    FileSearchConfigSchema,
    FunctionCallingConfig,
    ImageConfigSchema,
    SafetySettingsSchema,
    ThinkingConfigSchema,
)


class GeminiConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from GeminiConfigSchema for IDE autocomplete support."""

    api_key: str
    base_url: str
    api_version: str
    safety_settings: list[SafetySettingsSchema]
    code_execution: bool | dict[str, Any]
    context_cache: bool
    function_calling_config: FunctionCallingConfig
    response_modalities: list[str]
    google_search_retrieval: bool | dict[str, Any]
    file_search: FileSearchConfigSchema
    url_context: bool | dict[str, Any]
    temperature: float
    top_p: float
    top_k: int
    thinking_config: ThinkingConfigSchema
    max_output_tokens: int
    stop_sequences: list[str]


class GeminiImageConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from GeminiImageConfigSchema for IDE autocomplete support."""

    image_config: ImageConfigSchema


class GemmaConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from GemmaConfigSchema for IDE autocomplete support."""

    temperature: float


# --- Autogenerated Model References ---
gemini_20_flash: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-2.0-flash-001', config_schema=GeminiConfigDict)
gemini_20_flash_lite: ModelRef[GeminiConfigDict] = model_ref(
    'googleai/gemini-2.0-flash-lite-001', config_schema=GeminiConfigDict
)
gemini_25_flash_lite: ModelRef[GeminiConfigDict] = model_ref(
    'googleai/gemini-2.5-flash-lite', config_schema=GeminiConfigDict
)
gemini_3_flash_preview: ModelRef[GeminiConfigDict] = model_ref(
    'googleai/gemini-3-flash-preview', config_schema=GeminiConfigDict
)
gemini_31_flash_lite: ModelRef[GeminiConfigDict] = model_ref(
    'googleai/gemini-3.1-flash-lite', config_schema=GeminiConfigDict
)
gemini_31_pro_preview: ModelRef[GeminiConfigDict] = model_ref(
    'googleai/gemini-3.1-pro-preview', config_schema=GeminiConfigDict
)
gemini_35_flash: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-3.5-flash', config_schema=GeminiConfigDict)
gemini_flash_latest: ModelRef[GeminiConfigDict] = model_ref(
    'googleai/gemini-flash-latest', config_schema=GeminiConfigDict
)
gemini_pro_latest: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-pro-latest', config_schema=GeminiConfigDict)
vertexai_gemini_25_flash: ModelRef[GeminiConfigDict] = model_ref(
    'vertexai/gemini-2.5-flash', config_schema=GeminiConfigDict
)
vertexai_gemini_25_flash_lite: ModelRef[GeminiConfigDict] = model_ref(
    'vertexai/gemini-2.5-flash-lite', config_schema=GeminiConfigDict
)
vertexai_gemini_25_pro: ModelRef[GeminiConfigDict] = model_ref(
    'vertexai/gemini-2.5-pro', config_schema=GeminiConfigDict
)
vertexai_gemini_3_flash_preview: ModelRef[GeminiConfigDict] = model_ref(
    'vertexai/gemini-3-flash-preview', config_schema=GeminiConfigDict
)
gemini_25_flash_image: ModelRef[GeminiImageConfigDict] = model_ref(
    'googleai/gemini-2.5-flash-image', config_schema=GeminiImageConfigDict
)
gemini_3_pro_image: ModelRef[GeminiImageConfigDict] = model_ref(
    'googleai/gemini-3-pro-image', config_schema=GeminiImageConfigDict
)
gemini_31_flash_image: ModelRef[GeminiImageConfigDict] = model_ref(
    'googleai/gemini-3.1-flash-image', config_schema=GeminiImageConfigDict
)
gemma_3_1b_it: ModelRef[GemmaConfigDict] = model_ref('googleai/gemma-3-1b-it', config_schema=GemmaConfigDict)
gemma_3_4b_it: ModelRef[GemmaConfigDict] = model_ref('googleai/gemma-3-4b-it', config_schema=GemmaConfigDict)
gemma_3_12b_it: ModelRef[GemmaConfigDict] = model_ref('googleai/gemma-3-12b-it', config_schema=GemmaConfigDict)
gemma_3_27b_it: ModelRef[GemmaConfigDict] = model_ref('googleai/gemma-3-27b-it', config_schema=GemmaConfigDict)


__all__ = [
    'GeminiConfigDict',
    'GeminiImageConfigDict',
    'GemmaConfigDict',
    'gemini_20_flash',
    'gemini_20_flash_lite',
    'gemini_25_flash_image',
    'gemini_25_flash_lite',
    'gemini_31_flash_image',
    'gemini_31_flash_lite',
    'gemini_31_pro_preview',
    'gemini_35_flash',
    'gemini_3_flash_preview',
    'gemini_3_pro_image',
    'gemini_flash_latest',
    'gemini_pro_latest',
    'gemma_3_12b_it',
    'gemma_3_1b_it',
    'gemma_3_27b_it',
    'gemma_3_4b_it',
    'vertexai_gemini_25_flash',
    'vertexai_gemini_25_flash_lite',
    'vertexai_gemini_25_pro',
    'vertexai_gemini_3_flash_preview',
]
