# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Any

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref

from .models.gemini import (
    FileSearchConfigSchema,
    FunctionCallingConfig,
    SafetySettingsSchema,
    ThinkingConfigSchema,
)


class GeminiConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from GeminiConfigSchema for IDE autocomplete support."""

    api_key: str
    base_url: str
    api_version: str
    safety_settings: list[SafetySettingsSchema]
    code_execution: bool | dict[str, Any]
    context_cache: bool
    function_calling_config: FunctionCallingConfig
    response_modalities: list[str]
    google_search_retrieval: bool | dict[str, Any]
    file_search: FileSearchConfigSchema
    url_context: bool | dict[str, Any]
    temperature: float
    top_p: float
    top_k: int
    thinking_config: ThinkingConfigSchema
    max_output_tokens: int
    stop_sequences: list[str]


# --- Autogenerated Model References ---
gemini_15_flash: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-1.5-flash', config=GeminiConfigDict)
gemini_15_pro: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-1.5-pro', config=GeminiConfigDict)
gemini_20_flash: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-2.0-flash', config=GeminiConfigDict)
gemini_flash_latest: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-flash-latest', config=GeminiConfigDict)
gemini_pro_latest: ModelRef[GeminiConfigDict] = model_ref('googleai/gemini-pro-latest', config=GeminiConfigDict)
