// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file was generated by jsonschemagen. DO NOT EDIT.

package exp

import (
	"github.com/firebase/genkit/go/ai"
	"github.com/firebase/genkit/go/core"
	"time"
)

// AbortSnapshotRequest is the input for the abortSnapshot companion action.
type AbortSnapshotRequest struct {
	// SnapshotID identifies the snapshot whose invocation should be aborted.
	SnapshotID string `json:"snapshotId"`
}

// AbortSnapshotResponse is the output of the abortSnapshot companion action.
type AbortSnapshotResponse struct {
	// SnapshotID echoes the requested snapshot ID.
	SnapshotID string `json:"snapshotId"`
	// Status is the snapshot's status after the abort attempt. For a
	// pending snapshot this is [SnapshotStatusAborted]. For an
	// already-terminal snapshot this is the existing terminal status (the
	// abort is a no-op).
	Status SnapshotStatus `json:"status,omitempty"`
}

// AgentInit is the input for starting an agent invocation.
// Provide either SnapshotID (to load from store) or State (direct state).
type AgentInit[State any] struct {
	// SnapshotID loads state from a persisted snapshot.
	// Mutually exclusive with State.
	SnapshotID string `json:"snapshotId,omitempty"`
	// State provides direct state for the invocation.
	// Mutually exclusive with SnapshotID.
	State *SessionState[State] `json:"state,omitempty"`
}

// AgentInput is the input sent to an agent during a conversation turn.
type AgentInput struct {
	// Detach signals that the client wishes to disconnect after this input is
	// accepted. The server writes a single pending snapshot (with empty
	// state), returns [AgentOutput] with that snapshot ID, and continues
	// processing any already-buffered inputs in a background context. The
	// pending snapshot is finalized with the cumulative final state once all
	// queued inputs are processed (or the snapshot is cancelled via
	// cancelSnapshot).
	Detach bool `json:"detach,omitempty"`
	// Messages contains the user's input for this turn.
	Messages []*ai.Message `json:"messages,omitempty"`
	// Resume provides options for resuming an interrupted generation.
	// Construct using [ai.ToolDef.RestartWith] / [ai.ToolDef.RespondWith]
	// parts. When set, the generate call resumes with these parts instead
	// of treating Messages as tool responses.
	Resume *ToolResume `json:"resume,omitempty"`
}

// ToolResume holds the parts that resume an interrupted agent turn.
// Mirrors [ai.GenerateActionResume] but is named for the tool-call
// callsite where it is set on an [AgentInput].
type ToolResume struct {
	// Respond contains tool response parts to send to the model when resuming.
	Respond []*ai.Part `json:"respond,omitempty"`
	// Restart contains tool request parts to restart when resuming.
	Restart []*ai.Part `json:"restart,omitempty"`
}

// AgentMetadata is the value placed under metadata["agent"] on an agent's
// action descriptor. It exposes capability information so the Dev UI and
// other reflective callers can render the right surface (e.g. hide the
// Abort button when the configured store doesn't support it) without
// round-tripping through the reflection API.
type AgentMetadata struct {
	// Abortable reports whether the agent's invocations can be aborted
	// (true when the store implements [SnapshotAborter]).
	Abortable bool `json:"abortable,omitempty"`
	// StateManagement reports who owns session state.
	StateManagement AgentStateManagement `json:"stateManagement,omitempty"`
}

// AgentOutput is the output when an agent invocation completes.
// It wraps AgentResult with framework-managed fields.
type AgentOutput[State any] struct {
	// Artifacts contains artifacts produced during the session.
	Artifacts []*Artifact `json:"artifacts,omitempty"`
	// Message is the last model response message from the conversation.
	Message *ai.Message `json:"message,omitempty"`
	// SnapshotID is the ID of the snapshot created at the end of this invocation.
	// Empty if no snapshot was created (callback returned false or no store configured).
	SnapshotID string `json:"snapshotId,omitempty"`
	// State contains the final conversation state.
	// Only populated when state is client-managed (no store configured).
	State *SessionState[State] `json:"state,omitempty"`
}

// AgentResult is the return value from an AgentFunc.
// It contains the user-specified outputs of the agent invocation.
type AgentResult struct {
	// Artifacts contains artifacts produced during the session.
	Artifacts []*Artifact `json:"artifacts,omitempty"`
	// Message is the last model response message from the conversation.
	Message *ai.Message `json:"message,omitempty"`
}

// AgentStateManagement enumerates who owns session state for an
// agent: "server" (a [SessionStore] is configured and snapshots are
// persisted server-side) or "client" (no store; state flows through
// invocation init / output).
type AgentStateManagement string

const (
	// AgentStateManagementServer indicates the agent is wired with
	// a [SessionStore] and persists snapshots server-side.
	AgentStateManagementServer AgentStateManagement = "server"
	// AgentStateManagementClient indicates the agent has no store;
	// session state is client-managed and round-trips through invocation
	// init and output.
	AgentStateManagementClient AgentStateManagement = "client"
)

// AgentStreamChunk represents a single item in the agent's output stream.
// Multiple fields can be populated in a single chunk.
type AgentStreamChunk[Stream any] struct {
	// Artifact contains a newly produced artifact.
	Artifact *Artifact `json:"artifact,omitempty"`
	// ModelChunk contains generation tokens from the model.
	ModelChunk *ai.ModelResponseChunk `json:"modelChunk,omitempty"`
	// Status contains user-defined structured status information.
	// The Stream type parameter defines the shape of this data.
	Status Stream `json:"status,omitempty"`
	// TurnEnd is non-nil when the agent has finished processing the current
	// input. It groups all turn-end signals (snapshot ID, etc.) so callers can
	// check a single field. When set, the client should stop iterating and may
	// send the next input.
	TurnEnd *TurnEnd `json:"turnEnd,omitempty"`
}

// Artifact represents a named collection of parts produced during a session.
// Examples: generated files, images, code snippets, diagrams, etc.
type Artifact struct {
	// Metadata contains additional artifact-specific data.
	Metadata map[string]any `json:"metadata,omitempty"`
	// Name identifies the artifact (e.g., "generated_code.go", "diagram.png").
	Name string `json:"name,omitempty"`
	// Parts contains the artifact content (text, media, etc.).
	Parts []*ai.Part `json:"parts"`
}

// GetSnapshotRequest is the input for an agent's getSnapshot companion
// action. The action is registered at `{agentName}/getSnapshot` when the
// agent is defined and is intended for Dev UI and client-side reconnect
// flows.
type GetSnapshotRequest struct {
	// SnapshotID identifies the snapshot to fetch.
	SnapshotID string `json:"snapshotId"`
}

// GetSnapshotResponse is the output of the getSnapshot companion action. It
// is a client-facing view of the stored snapshot: identifying metadata plus
// the session state, with [WithStateTransform] applied if configured.
//
// Unlike the raw [SessionSnapshot], this response intentionally omits
// internal fields (parent ID, event) and does not leak the snapshot
// envelope beyond what callers need to repopulate a UI.
type GetSnapshotResponse[State any] struct {
	// CreatedAt is when the snapshot record was first written.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Error is the structured failure information; populated when Status
	// is [SnapshotStatusFailed].
	Error *core.GenkitError `json:"error,omitempty"`
	// SnapshotID echoes the requested snapshot ID.
	SnapshotID string `json:"snapshotId"`
	// State is the session state captured by the snapshot, after any
	// configured transform. Empty when Status is pending or error.
	State *SessionState[State] `json:"state,omitempty"`
	// Status is the lifecycle state of the snapshot. See [SnapshotStatus].
	Status SnapshotStatus `json:"status,omitempty"`
	// UpdatedAt is when the snapshot record was last written. Equals
	// CreatedAt for snapshots that have not been rewritten.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// SessionState is the portable conversation state that flows between client
// and server. It contains only the data needed for conversation continuity.
type SessionState[State any] struct {
	// Artifacts are named collections of parts produced during the conversation.
	Artifacts []*Artifact `json:"artifacts,omitempty"`
	// Custom is the user-defined state associated with this conversation.
	Custom State `json:"custom,omitempty"`
	// Messages is the conversation history (user/model exchanges).
	// Does NOT include prompt-rendered messages — those are rendered fresh each turn.
	Messages []*ai.Message `json:"messages,omitempty"`
}

// SnapshotEvent identifies what triggered a snapshot.
type SnapshotEvent string

const (
	// TurnEnd indicates the snapshot was triggered at the end of a turn.
	SnapshotEventTurnEnd SnapshotEvent = "turnEnd"
	// InvocationEnd indicates the snapshot was triggered at the end of the invocation.
	SnapshotEventInvocationEnd SnapshotEvent = "invocationEnd"
	// Detach indicates the snapshot was created when the client detached the
	// invocation and the flow continues in the background. The snapshot is
	// initially written with [SnapshotStatusPending] and rewritten with a
	// terminal status once the background work finishes.
	SnapshotEventDetach SnapshotEvent = "detach"
)

// SnapshotMetadata is the metadata-only projection of a [SessionSnapshot]:
// identifying fields, lifecycle timestamps, and status. Returned by store
// operations that surface a snapshot's lifecycle state without paying for
// a full state read.
type SnapshotMetadata struct {
	// CreatedAt is when the snapshot was first written.
	CreatedAt time.Time `json:"createdAt"`
	// Error is the structured failure information for a snapshot in
	// [SnapshotStatusFailed].
	Error *core.GenkitError `json:"error,omitempty"`
	// Event is what triggered this snapshot.
	Event SnapshotEvent `json:"event"`
	// ParentID is the ID of the previous snapshot in this timeline.
	ParentID string `json:"parentId,omitempty"`
	// SnapshotID is the unique identifier for this snapshot.
	SnapshotID string `json:"snapshotId"`
	// Status is the lifecycle state of this snapshot.
	Status SnapshotStatus `json:"status,omitempty"`
	// UpdatedAt is when the snapshot was last written.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// SnapshotStatus describes the lifecycle state of a snapshot. Snapshots
// written for synchronous turns or invocations are always
// [SnapshotStatusSucceeded] (an empty value is also treated as succeeded
// for backwards compatibility).
//
// When a client sets [AgentInput.Detach], the server writes a single
// snapshot with [SnapshotStatusPending] (and empty state) and returns its
// ID immediately. Background processing then either rewrites that snapshot
// with the cumulative final state and [SnapshotStatusSucceeded] /
// [SnapshotStatusFailed] when the agent finishes, or with
// [SnapshotStatusAborted] if the client called abortSnapshot in the
// meantime.
type SnapshotStatus string

const (
	// SnapshotStatusPending indicates a detached invocation is still
	// processing the queued inputs. The snapshot will be rewritten with a
	// terminal status once the flow exits.
	SnapshotStatusPending SnapshotStatus = "pending"
	// SnapshotStatusSucceeded indicates the snapshot captures a settled state.
	SnapshotStatusSucceeded SnapshotStatus = "succeeded"
	// SnapshotStatusAborted indicates the snapshot's invocation was
	// aborted via the abortSnapshot companion action while detached.
	SnapshotStatusAborted SnapshotStatus = "aborted"
	// SnapshotStatusFailed indicates the invocation terminated with an error.
	// The snapshot's Error field describes the failure and resume is
	// rejected with that same error.
	SnapshotStatusFailed SnapshotStatus = "failed"
)

// TurnEnd groups the signals emitted when an agent turn finishes.
// A TurnEnd value is emitted exactly once per turn, regardless of whether a
// snapshot was persisted.
type TurnEnd struct {
	// SnapshotID is the ID of the snapshot persisted at the end of this turn.
	// Empty if no snapshot was created (callback returned false or no store
	// configured, or snapshots were suspended after detach).
	SnapshotID string `json:"snapshotId,omitempty"`
}
