// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file was generated by jsonschemagen. DO NOT EDIT.

package core

// genkitErrorWire is the on-the-wire shape of a [GenkitError]: the
// canonical Genkit error format ({status, message, details}) shared
// across runtimes (RuntimeError in the JSON schema). GenkitError's
// MarshalJSON, UnmarshalJSON, and JSONSchema delegate to it; fields that
// exist for in-process use (HTTPCode, Source, the wrapped error) are not
// part of it.
type genkitErrorWire struct {
	// Details is optional structured information describing the failure.
	Details map[string]any `json:"details,omitempty"`
	// Message is the human-readable error message.
	Message string `json:"message"`
	// Status is the canonical status name (e.g. INTERNAL, FAILED_PRECONDITION).
	Status StatusName `json:"status,omitempty"`
}
