# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Any

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref


class ClaudeConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from ClaudeConfigSchema for IDE autocomplete support."""

    max_tokens_to_sample: int
    thinking: dict[str, Any]


# --- Autogenerated Model References ---
claude_opus_4_8: ModelRef[ClaudeConfigDict] = model_ref('anthropic/claude-opus-4-8', config=ClaudeConfigDict)
claude_opus_4_7: ModelRef[ClaudeConfigDict] = model_ref('anthropic/claude-opus-4-7', config=ClaudeConfigDict)
