#!/usr/bin/env python3
# Copyright 2026 Google LLC
# SPDX-License-Identifier: Apache-2.0

import os
from typing import get_type_hints
import google.genai.types
import PIL.Image
import mcp.types
import mcp.client.session

def to_camel_case(snake_str: str) -> str:
    components = snake_str.split('_')
    return components[0] + ''.join(x.title() for x in components[1:])

def clean_type_str(t) -> str:
    s = str(t)
    s = s.replace('NoneType', 'None')
    s = s.replace('typing._UnionGenericAlias', 'typing.Any')
    s = s.replace('types.GenericAlias', 'typing.Any')
    s = s.replace('types.UnionType', 'typing.Any')
    return s

def generate_typed_dict() -> str:
    model = google.genai.types.GenerateContentConfig
    
    code = []
    code.append("# This file is automatically generated. Do not edit manually.")
    code.append("import typing")
    code.append("import google.genai.types")
    code.append("import PIL.Image")
    code.append("import mcp.types")
    code.append("import mcp.client.session")
    code.append("import types")
    code.append("")
    code.append("class GeminiConfigDict(typing.TypedDict, total=False):")
    code.append("    \"\"\"TypedDict representation of Gemini generation configurations.\"\"\"")
    
    for name, field in model.model_fields.items():
        type_str = clean_type_str(field.annotation)
        # 1. Add snake_case version
        code.append(f"    {name}: {type_str}")
        
        # 2. Add camelCase version if different
        camel_name = to_camel_case(name)
        if camel_name != name:
            code.append(f"    {camel_name}: {type_str}")
            
    return "\n".join(code)

def main():
    target_path = os.path.join(
        os.path.dirname(os.path.dirname(__file__)),
        'plugins/google-genai/src/genkit/plugins/google_genai/models/gemini_types.py'
    )
    print(f"Generating model config types to {target_path}...")
    with open(target_path, 'w') as f:
        f.write(generate_typed_dict())
    print("Done!")

if __name__ == '__main__':
    main()
