#!/usr/bin/env python3
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

"""Tool to generate plugin configuration TypedDicts (*ConfigDict), ModelRef exports, and maintain __init__.py autogenerated exports."""

import ast
import re
import sys
from pathlib import Path
from typing import Any

import yaml

HEADER = """# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Any, Literal
from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref
"""

EXPORTS_START = '# === AUTOGENERATED EXPORTS START ==='
EXPORTS_END = '# === AUTOGENERATED EXPORTS END ==='


def ast_to_type_str(node: ast.AST | None) -> str:
    if node is None:
        return 'Any'
    return ast.unparse(node)


def strip_optional(type_str: str) -> str:
    type_str = type_str.strip()
    if type_str.endswith('| None'):
        return type_str[:-6].strip()
    if type_str.startswith('Optional[') and type_str.endswith(']'):
        return type_str[9:-1].strip()
    return type_str


def collect_referenced_types(node: ast.AST) -> set[str]:
    refs = set()
    for child in ast.walk(node):
        if isinstance(child, ast.Name):
            name = child.id
            if name[0].isupper() and name not in ('Any', 'Literal', 'Optional', 'Union', 'List', 'Dict', 'Mapping'):
                refs.add(name)
    return refs


def generate_typedict_from_ast(class_node: ast.ClassDef, typedict_name: str) -> tuple[str, set[str]]:
    lines = [
        f'class {typedict_name}(CommonModelConfigDict, total=False):',
        f'    """Typed dictionary configuration generated from {class_node.name} for IDE autocomplete support."""',
        '',
    ]
    fields_found = 0
    referenced_symbols = set()
    for item in class_node.body:
        if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
            field_name = item.target.id
            if field_name.startswith('_') or field_name in ('model_config',):
                continue
            if item.annotation:
                referenced_symbols.update(collect_referenced_types(item.annotation))
            raw_type = ast_to_type_str(item.annotation)
            if raw_type.startswith('Annotated['):
                inner = raw_type[10:-1].split(',')[0].strip()
                raw_type = inner
            clean_type = strip_optional(raw_type)
            lines.append(f'    {field_name}: {clean_type}')
            fields_found += 1

    if fields_found == 0:
        lines.append('    pass')
    return '\n'.join(lines), referenced_symbols


def infer_typedict_name(schema_name: str) -> str:
    if schema_name.endswith('Schema'):
        return schema_name[:-6] + 'Dict'
    if schema_name.endswith('Config'):
        return schema_name + 'Dict'
    return schema_name + 'Dict'


def infer_export_name(model_name: str) -> str:
    base = model_name.split('/')[-1]
    base = base.split('@')[0]
    name = re.sub(r'[^a-zA-Z0-9]', '_', base)
    name = re.sub(r'_+', '_', name).strip('_')
    return name


def process_models_yaml(yaml_path: Path) -> tuple[Path, str, list[str]]:
    data = yaml.safe_load(yaml_path.read_text(encoding='utf-8'))
    default_schema = data.get('default_schema')
    if not default_schema:
        raise ValueError(f'{yaml_path} must define default_schema')

    plugin_dir = yaml_path.parent
    src_dir = plugin_dir / 'src'
    target_file = None
    for py_file in src_dir.rglob('*.py'):
        if py_file.name == '_generated.py':
            continue
        content = py_file.read_text(encoding='utf-8')
        if f'class {default_schema}(' in content:
            target_file = py_file
            break

    if not target_file:
        raise ValueError(f'Could not locate target file defining class {default_schema} in {src_dir}')

    pkg_dir = target_file.parent
    while pkg_dir.parent != src_dir and pkg_dir != src_dir:
        if (pkg_dir.parent / '__init__.py').exists():
            pkg_dir = pkg_dir.parent
        else:
            break

    rel_path = target_file.relative_to(pkg_dir)
    mod_path = '.' + '.'.join(rel_path.with_suffix('').parts)

    tree = ast.parse(target_file.read_text(encoding='utf-8'), filename=str(target_file))
    class_map = {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}

    schemas_to_generate = {default_schema}
    for model_entry in data.get('models', []):
        if 'schema' in model_entry:
            schemas_to_generate.add(model_entry['schema'])

    output_blocks = []
    all_referenced = set()
    exported_symbols = []
    for schema_name in sorted(schemas_to_generate):
        if schema_name in class_map:
            dict_name = infer_typedict_name(schema_name)
            code_block, refs = generate_typedict_from_ast(class_map[schema_name], dict_name)
            output_blocks.append(code_block)
            all_referenced.update(refs)
            exported_symbols.append(dict_name)

    imported_symbols = sorted(all_referenced)
    imports_str = ''
    if imported_symbols:
        symbols_fmt = ', '.join(imported_symbols)
        imports_str = f'from {mod_path} import {symbols_fmt}\n\n'

    exports = ['# --- Autogenerated Model References ---']
    for model_entry in data.get('models', []):
        model_name = model_entry['name']
        export_name = model_entry.get('export') or infer_export_name(model_name)
        schema_name = model_entry.get('schema', default_schema)
        dict_name = infer_typedict_name(schema_name)
        exports.append(f"{export_name}: ModelRef[{dict_name}] = model_ref('{model_name}', config={dict_name})")
        exported_symbols.append(export_name)

    exported_symbols.sort()
    all_list = ',\n    '.join(repr(s) for s in exported_symbols)
    all_block = f'__all__ = [\n    {all_list},\n]'

    generated_file = pkg_dir / '_generated.py'
    full_content = HEADER + imports_str + '\n\n'.join(output_blocks) + '\n\n\n' + '\n'.join(exports) + '\n\n\n' + all_block + '\n'
    return generated_file, full_content, exported_symbols


def update_in_place(yaml_path: Path) -> None:
    generated_file, content, exported_symbols = process_models_yaml(yaml_path)
    generated_file.write_text(content, encoding='utf-8')
    print(f'Wrote {generated_file}')

    pkg_dir = generated_file.parent
    init_file = pkg_dir / '__init__.py'
    if init_file.exists():
        init_content = init_file.read_text(encoding='utf-8')
        symbols_str = ',\n    '.join(exported_symbols)
        exports_block = f"{EXPORTS_START}\nfrom ._generated import (\n    {symbols_str},\n)\nfrom ._generated import __all__ as _generated_all\n{EXPORTS_END}"

        if EXPORTS_START in init_content and EXPORTS_END in init_content:
            before = init_content.split(EXPORTS_START)[0].rstrip()
            after = init_content.split(EXPORTS_END)[1].lstrip()
            new_init = f'{before}\n\n{exports_block}\n'
            if after:
                new_init += f'\n{after}'
        else:
            # Find insertion point before first def, class, or __all__
            lines = init_content.splitlines()
            insert_idx = len(lines)
            for idx, line in enumerate(lines):
                if line.startswith('def ') or line.startswith('class ') or line.startswith('__all__'):
                    insert_idx = idx
                    break
            before_lines = lines[:insert_idx]
            after_lines = lines[insert_idx:]
            new_init = '\n'.join(before_lines).rstrip() + f'\n\n{exports_block}\n\n' + '\n'.join(after_lines).lstrip() + '\n'
        init_file.write_text(new_init, encoding='utf-8')
        print(f'Updated {init_file}')


def main() -> None:
    args = sys.argv[1:]
    in_place = False
    if '--in-place' in args:
        in_place = True
        args.remove('--in-place')

    if not args:
        print('Usage: generate_config_dicts.py [--in-place] <path/to/models.yaml ...>')
        return

    for arg in args:
        p = Path(arg)
        if p.name.endswith('.yaml'):
            if in_place:
                update_in_place(p)
            else:
                _, code, _ = process_models_yaml(p)
                print(code)


if __name__ == '__main__':
    main()
