#!/usr/bin/env python3
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

"""Generate plugin configuration TypedDicts (*ConfigDict) and ModelRef exports.

In Python, static type checkers enforce nominal typing for Pydantic `BaseModel` classes,
while `TypedDict` is the only construct that provides static key autocompletion and type checking
for raw dictionary literals (`config={...}`) at the API surface.

To avoid requiring plugin authors to manually author and synchronize two copies of every schema
(the `TypedDict` for IDE autocompletion and the `BaseModel` for runtime data validation),
this tool performs AST codegen from `models.yaml`. It inspects the Pydantic schema classes via
AST without runtime side-effects and generates the synchronized `TypedDict` twin (`*ConfigDict`)
and `ModelRef` definitions inside each plugin's `_generated.py` file.
"""

import ast
import re
import sys
from pathlib import Path

import yaml

HEADER = """# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Any, Literal
from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref
"""


def ast_to_type_str(node: ast.AST | None) -> str:
    """Convert an AST node into a clean string representation of a Python type."""
    if node is None:
        return 'Any'
    return ast.unparse(node)


def strip_optional(type_str: str) -> str:
    """Remove trailing | None or surrounding Optional[...] from a type string."""
    type_str = type_str.strip()
    if type_str.endswith('| None'):
        return type_str[:-6].strip()
    if type_str.startswith('Optional[') and type_str.endswith(']'):
        return type_str[9:-1].strip()
    return type_str


def collect_referenced_types(node: ast.AST) -> set[str]:
    """Collect all capitalized type symbol names referenced inside an AST annotation node."""
    refs = set()
    for child in ast.walk(node):
        if isinstance(child, ast.Name):
            name = child.id
            if name[0].isupper() and name not in ('Any', 'Literal', 'Optional', 'Union', 'List', 'Dict', 'Mapping'):
                refs.add(name)
    return refs


def unwrap_annotated(node: ast.AST | None) -> ast.AST | None:
    """Extract the underlying type node from an Annotated[Type, ...] AST subscript."""
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name) and node.value.id == 'Annotated':
        slice_node = node.slice
        if isinstance(slice_node, ast.Tuple) and slice_node.elts:
            return slice_node.elts[0]
        if hasattr(slice_node, 'value') and isinstance(slice_node.value, ast.Tuple) and slice_node.value.elts:
            return slice_node.value.elts[0]
    return node


def generate_typedict_from_ast(class_node: ast.ClassDef, typedict_name: str) -> tuple[str, set[str]]:
    """Synthesize a TypedDict class definition string and referenced symbols from a Pydantic AST class node."""
    lines = [
        f'class {typedict_name}(CommonModelConfigDict, total=False):',
        f'    """Typed dictionary configuration generated from {class_node.name} for IDE autocomplete support."""',
        '',
    ]
    fields_found = 0
    referenced_symbols = set()
    for item in class_node.body:
        if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
            field_name = item.target.id
            if field_name.startswith('_') or field_name in ('model_config',):
                continue
            annotation_node = unwrap_annotated(item.annotation)
            if annotation_node:
                referenced_symbols.update(collect_referenced_types(annotation_node))
            raw_type = ast_to_type_str(annotation_node)
            clean_type = strip_optional(raw_type)
            lines.append(f'    {field_name}: {clean_type}')
            fields_found += 1

    if fields_found == 0:
        lines.append('    pass')
    return '\n'.join(lines), referenced_symbols


def infer_typedict_name(schema_name: str) -> str:
    """Derive the TypedDict class name from a Pydantic schema class name."""
    if schema_name.endswith('Schema'):
        return schema_name[:-6] + 'Dict'
    if schema_name.endswith('Config'):
        return schema_name + 'Dict'
    return schema_name + 'Dict'


def infer_export_name(model_name: str) -> str:
    """Infer a clean Pythonic variable name from a provider model string identifier."""
    base = model_name.split('/')[-1]
    base = base.split('@')[0]
    name = re.sub(r'[^a-zA-Z0-9]', '_', base)
    name = re.sub(r'_+', '_', name).strip('_')
    if name and name[0].isdigit():
        name = f'model_{name}'
    return name


def process_models_yaml(yaml_path: Path) -> tuple[Path, str, list[str]]:
    """Parse a models.yaml file and return the target file path, synthesized Python content, and exported symbols."""
    data = yaml.safe_load(yaml_path.read_text(encoding='utf-8'))
    default_schema = data.get('default_schema')
    if not default_schema:
        raise ValueError(f'{yaml_path} must define default_schema')

    plugin_dir = yaml_path.parent
    src_dir = plugin_dir / 'src'
    target_file = None
    for py_file in src_dir.rglob('*.py'):
        if py_file.name == '_generated.py':
            continue
        content = py_file.read_text(encoding='utf-8')
        if re.search(rf'class\s+{default_schema}\b', content):
            target_file = py_file
            break

    if not target_file:
        raise ValueError(f'Could not locate target file defining class {default_schema} in {src_dir}')

    pkg_dir = target_file.parent
    while pkg_dir.parent != src_dir and pkg_dir != src_dir:
        if (pkg_dir.parent / '__init__.py').exists():
            pkg_dir = pkg_dir.parent
        else:
            break

    rel_path = target_file.relative_to(pkg_dir)
    mod_path = '.' + '.'.join(rel_path.with_suffix('').parts)

    tree = ast.parse(target_file.read_text(encoding='utf-8'), filename=str(target_file))
    class_map = {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}

    schemas_to_generate = {default_schema}
    for model_entry in data.get('models', []):
        if 'schema' in model_entry:
            schemas_to_generate.add(model_entry['schema'])

    output_blocks = []
    all_referenced = set()
    exported_symbols = []
    for schema_name in sorted(schemas_to_generate):
        if schema_name in class_map:
            dict_name = infer_typedict_name(schema_name)
            code_block, refs = generate_typedict_from_ast(class_map[schema_name], dict_name)
            output_blocks.append(code_block)
            all_referenced.update(refs)
            exported_symbols.append(dict_name)

    imported_symbols = sorted(all_referenced)
    imports_str = ''
    if imported_symbols:
        symbols_fmt = ', '.join(imported_symbols)
        imports_str = f'from {mod_path} import {symbols_fmt}\n\n'

    exports = ['# --- Autogenerated Model References ---']
    for model_entry in data.get('models', []):
        model_name = model_entry['name']
        export_name = model_entry.get('export') or infer_export_name(model_name)
        schema_name = model_entry.get('schema', default_schema)
        dict_name = infer_typedict_name(schema_name)
        exports.append(f"{export_name}: ModelRef[{dict_name}] = model_ref('{model_name}', config_schema={dict_name})")
        exported_symbols.append(export_name)

    exported_symbols.sort()
    all_list = ',\n    '.join(repr(s) for s in exported_symbols)
    all_block = f'__all__ = [\n    {all_list},\n]'

    generated_file = pkg_dir / '_generated.py'
    parts = [HEADER, imports_str, '\n\n'.join(output_blocks), '\n\n\n', '\n'.join(exports), '\n\n\n', all_block, '\n']
    full_content = ''.join(parts)
    return generated_file, full_content, exported_symbols


def update_in_place(yaml_path: Path) -> None:
    """Generate and overwrite the _generated.py file for the given models.yaml specification."""
    generated_file, content, _ = process_models_yaml(yaml_path)
    generated_file.write_text(content, encoding='utf-8')
    print(f'Wrote {generated_file}')  # noqa: T201


def main() -> None:
    """CLI entry point for running the config dict and model reference generator."""
    args = sys.argv[1:]
    in_place = False
    if '--in-place' in args:
        in_place = True
        args.remove('--in-place')

    if not args:
        print('Usage: generate_config_dicts.py [--in-place] <path/to/models.yaml ...>')  # noqa: T201
        return

    for arg in args:
        p = Path(arg)
        if p.name.endswith('.yaml'):
            if in_place:
                update_in_place(p)
            else:
                _, code, _ = process_models_yaml(p)
                print(code)  # noqa: T201


if __name__ == '__main__':
    main()
