#!/usr/bin/env python3
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

"""Tool to generate or verify TypedDict configuration classes (*ConfigDict) and ModelRef exports from models.yaml in plugins."""

import ast
import sys
from pathlib import Path
from typing import Any

import yaml

START_MARKER = '# === AUTOGENERATED CONFIG DICTS AND MODEL REFS START ==='
END_MARKER = '# === AUTOGENERATED CONFIG DICTS AND MODEL REFS END ==='


def ast_to_type_str(node: ast.AST | None) -> str:
    """Convert an AST annotation node back to a readable Python type string."""
    if node is None:
        return 'Any'
    return ast.unparse(node)


def strip_optional(type_str: str) -> str:
    """Strip top-level '| None' or 'Optional[...]' from a type string for TypedDict ergonomics."""
    type_str = type_str.strip()
    if type_str.endswith('| None'):
        return type_str[:-6].strip()
    if type_str.startswith('Optional[') and type_str.endswith(']'):
        return type_str[9:-1].strip()
    return type_str


def generate_typedict_from_ast(class_node: ast.ClassDef, typedict_name: str) -> str:
    """Generate a TypedDict definition string from a Pydantic ClassDef AST node."""
    lines = [
        f'class {typedict_name}(CommonModelConfigDict, total=False):',
        f'    """Typed dictionary configuration generated from {class_node.name} for IDE autocomplete support."""',
        '',
    ]
    fields_found = 0
    for item in class_node.body:
        if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
            field_name = item.target.id
            if field_name.startswith('_') or field_name in ('model_config',):
                continue
            raw_type = ast_to_type_str(item.annotation)
            if raw_type.startswith('Annotated['):
                inner = raw_type[10:-1].split(',')[0].strip()
                raw_type = inner
            clean_type = strip_optional(raw_type)
            lines.append(f'    {field_name}: {clean_type}')
            fields_found += 1

    if fields_found == 0:
        lines.append('    pass')
    return '\n'.join(lines)


def infer_typedict_name(schema_name: str) -> str:
    if schema_name.endswith('Schema'):
        return schema_name[:-6] + 'Dict'
    if schema_name.endswith('Config'):
        return schema_name + 'Dict'
    return schema_name + 'Dict'


def process_models_yaml(yaml_path: Path) -> tuple[Path, str]:
    """Process a models.yaml configuration file and return (target_file_path, generated_code)."""
    data = yaml.safe_load(yaml_path.read_text(encoding='utf-8'))
    default_schema = data.get('default_schema')
    if not default_schema:
        raise ValueError(f'{yaml_path} must define default_schema')

    plugin_dir = yaml_path.parent
    src_dir = plugin_dir / 'src'
    target_file = None
    for py_file in src_dir.rglob('*.py'):
        content = py_file.read_text(encoding='utf-8')
        if f'class {default_schema}(' in content:
            target_file = py_file
            break

    if not target_file:
        raise ValueError(f'Could not locate target file defining class {default_schema} in {src_dir}')

    tree = ast.parse(target_file.read_text(encoding='utf-8'), filename=str(target_file))
    class_map = {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}

    schemas_to_generate = {default_schema}
    for model_entry in data.get('models', []):
        if 'schema' in model_entry:
            schemas_to_generate.add(model_entry['schema'])

    output_blocks = []
    for schema_name in sorted(schemas_to_generate):
        if schema_name in class_map:
            dict_name = infer_typedict_name(schema_name)
            output_blocks.append(generate_typedict_from_ast(class_map[schema_name], dict_name))

    exports = ['# --- Autogenerated Model References ---']
    for model_entry in data.get('models', []):
        model_name = model_entry['name']
        export_name = model_entry['export']
        schema_name = model_entry.get('schema', default_schema)
        dict_name = infer_typedict_name(schema_name)
        exports.append(f"{export_name}: ModelRef[{dict_name}] = model_ref('{model_name}', config={dict_name})")

    generated_code = '\n\n\n'.join(output_blocks + ['\n'.join(exports)])
    full_block = f'{START_MARKER}\n{generated_code}\n{END_MARKER}'
    return target_file, full_block


def update_in_place(yaml_path: Path) -> None:
    target_file, full_block = process_models_yaml(yaml_path)
    content = target_file.read_text(encoding='utf-8')
    if START_MARKER in content and END_MARKER in content:
        before = content.split(START_MARKER)[0].rstrip()
        after = content.split(END_MARKER)[1].lstrip()
        new_content = f'{before}\n\n\n{full_block}\n'
        if after:
            new_content += f'\n{after}'
    else:
        new_content = content.rstrip() + f'\n\n\n{full_block}\n'
    target_file.write_text(new_content, encoding='utf-8')
    print(f'Updated {target_file}')


def main() -> None:
    args = sys.argv[1:]
    in_place = False
    if '--in-place' in args:
        in_place = True
        args.remove('--in-place')

    if not args:
        print('Usage: generate_config_dicts.py [--in-place] <path/to/models.yaml ...>')
        return

    for arg in args:
        p = Path(arg)
        if p.name.endswith('.yaml'):
            if in_place:
                update_in_place(p)
            else:
                _, code = process_models_yaml(p)
                print(code)


if __name__ == '__main__':
    main()
