# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref


class AnthropicConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from AnthropicConfigSchema for IDE autocomplete support."""

    pass


# --- Autogenerated Model References ---
claude_3_5_sonnet: ModelRef[AnthropicConfigDict] = model_ref(
    'modelgarden/anthropic/claude-3-5-sonnet-v2@20241022', config_schema=AnthropicConfigDict
)
claude_3_5_haiku: ModelRef[AnthropicConfigDict] = model_ref(
    'modelgarden/anthropic/claude-3-5-haiku@20241022', config_schema=AnthropicConfigDict
)
claude_3_7_sonnet: ModelRef[AnthropicConfigDict] = model_ref(
    'modelgarden/anthropic/claude-3-7-sonnet@20250219', config_schema=AnthropicConfigDict
)


__all__ = [
    'AnthropicConfigDict',
    'claude_3_5_haiku',
    'claude_3_5_sonnet',
    'claude_3_7_sonnet',
]
