# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Literal

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref


class OllamaConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from OllamaConfig for IDE autocomplete support."""

    think: bool | Literal['low', 'medium', 'high']
    keep_alive: float | str
    num_ctx: int
    min_p: float
    seed: int
    num_predict: int
    repeat_penalty: float


# --- Autogenerated Model References ---
llama3_2: ModelRef[OllamaConfigDict] = model_ref('ollama/llama3.2', config_schema=OllamaConfigDict)
llama3_1: ModelRef[OllamaConfigDict] = model_ref('ollama/llama3.1', config_schema=OllamaConfigDict)
mistral: ModelRef[OllamaConfigDict] = model_ref('ollama/mistral', config_schema=OllamaConfigDict)
gemma2: ModelRef[OllamaConfigDict] = model_ref('ollama/gemma2', config_schema=OllamaConfigDict)


__all__ = [
    'OllamaConfigDict',
    'gemma2',
    'llama3_1',
    'llama3_2',
    'mistral',
]
