# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref


class OllamaConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from OllamaConfigSchema for IDE autocomplete support."""

    num_predict: int
    repeat_penalty: float
    seed: int


# --- Autogenerated Model References ---
llama3_2: ModelRef[OllamaConfigDict] = model_ref('ollama/llama3.2', config=OllamaConfigDict)
llama3_1: ModelRef[OllamaConfigDict] = model_ref('ollama/llama3.1', config=OllamaConfigDict)
mistral: ModelRef[OllamaConfigDict] = model_ref('ollama/mistral', config=OllamaConfigDict)
gemma2: ModelRef[OllamaConfigDict] = model_ref('ollama/gemma2', config=OllamaConfigDict)


__all__ = [
    'OllamaConfigDict',
    'gemma2',
    'llama3_1',
    'llama3_2',
    'mistral',
]
