# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Go tests and checks

on:
  pull_request:
    paths:
      - "go/**"
      - "genkit-tools/**"
      - "tests/specs/**"
      - ".github/workflows/go.yml"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25.x', '1.26.x']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Set up Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          pnpm install
          cd genkit-tools && pnpm install

      - name: Generate JSON Schema from Zod
        run: npm --prefix genkit-tools run export:schemas

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check if generated code is up to date
        run: bash .github/workflows/scripts/check-generated-go.sh

      - name: Check gofmt
        run: |
          fmt_files=$(go fmt ./...)
          if [ -n "$fmt_files" ]; then
            echo "Go files are not formatted. Please run 'go fmt ./...' and commit the changes:"
            echo "$fmt_files"
            exit 1
          fi
        working-directory: ./go

      - name: Run tests
        run: go test -C go -v ./...
