# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0
#
# DO NOT EDIT: Generated by `generate_plugin_configs` from `models.yaml`.

from __future__ import annotations

from typing import Any, Literal

from genkit._core._model import CommonModelConfigDict
from genkit.model import ModelRef, model_ref

from .typing import PromptCacheRetention, ReasoningEffort, ServiceTier, Verbosity


class OpenAIConfigDict(CommonModelConfigDict, total=False):
    """Typed dictionary configuration generated from OpenAIConfig for IDE autocomplete support."""

    model: str
    temperature: float
    top_p: float
    max_tokens: int
    max_completion_tokens: int
    stop: str | list[str]
    stream: bool
    n: int
    frequency_penalty: float
    presence_penalty: float
    logit_bias: dict[str, int]
    logprobs: bool
    top_logprobs: int
    seed: int
    user: str
    safety_identifier: str
    prompt_cache_key: str
    prompt_cache_retention: PromptCacheRetention
    reasoning_effort: ReasoningEffort
    verbosity: Verbosity
    parallel_tool_calls: bool
    response_format: dict[str, Any]
    modalities: list[Literal['text', 'audio']]
    audio: dict[str, Any]
    service_tier: ServiceTier
    store: bool
    metadata: dict[str, str]
    prediction: dict[str, Any]
    stream_options: dict[str, Any]
    web_search_options: dict[str, Any]


# --- Autogenerated Model References ---
gpt_4o: ModelRef[OpenAIConfigDict] = model_ref('openai/gpt-4o', config=OpenAIConfigDict)
gpt_4o_mini: ModelRef[OpenAIConfigDict] = model_ref('openai/gpt-4o-mini', config=OpenAIConfigDict)
o1: ModelRef[OpenAIConfigDict] = model_ref('openai/o1', config=OpenAIConfigDict)
o1_mini: ModelRef[OpenAIConfigDict] = model_ref('openai/o1-mini', config=OpenAIConfigDict)
o3_mini: ModelRef[OpenAIConfigDict] = model_ref('openai/o3-mini', config=OpenAIConfigDict)


__all__ = [
    'OpenAIConfigDict',
    'gpt_4o',
    'gpt_4o_mini',
    'o1',
    'o1_mini',
    'o3_mini',
]
